### ISSUE TITLE
Compile error ltiff

### ISSUE THREAD

**Issue by xin-xinhanggao** [RemiFusade2/ImageAnalogies#1]
Hello! When I type make to compile the source files, I get the error message like this:
      make: *** No rule to make target `-ltiff', needed by `AnalogImage'.  Stop.
I wonder what is the meaning of ltiff, thanks for your help.

**Comment by RemiFusade2** [comment]
Hello! This project is 7 years old and we haven't updated it ever since so maybe it uses deprecated stuff.
-ltiff is supposed to tell gcc to use libtiff library
you can use -L [path to libtiff on your machine] instead.

I'm sorry, I can't help you much more than this.
Good luck !

**Comment by xin-xinhanggao** [comment]
Thanks for your help!
